#pragma once
#include "pixel.h"

#define CL_BLUE 0     // Светлое небо
#define CL_BLUE_D 1   // Темное небо
#define CL_YELLOW 2   // Светлая часть стрелки солнца
#define CL_YELLOW_D 3 // Темная часть стрелки солнца
#define CL_WHITE 4    // Светлая часть стрелки луны
#define CL_WHITE_D 5  // Темная часть стрелки луны

static const Pix CL_0[] = {
    {CL_WHITE, 11},
    {CL_WHITE, 19},
    {CL_WHITE, 27},
    {CL_WHITE, 35},
    {CL_WHITE, 43},
    {CL_WHITE_D, 18},
    {CL_WHITE_D, 10},
    {CL_WHITE_D, 3},
    {CL_WHITE_D, 12},
    {CL_WHITE_D, 20},
    {CL_BLUE, 48},
    {CL_BLUE, 49},
    {CL_BLUE, 50},
    {CL_BLUE, 51},
    {CL_BLUE, 52},
    {CL_BLUE, 53},
    {CL_BLUE, 54},
    {CL_BLUE_D, 40},
    {CL_BLUE_D, 41},
    {CL_BLUE_D, 42},
    {CL_BLUE_D, 44},
    {CL_BLUE_D, 45},
    {CL_BLUE_D, 46},
};
static const Pix CL_1[] = {
    {CL_WHITE, 12},
    {CL_WHITE, 20},
    {CL_WHITE, 28},
    {CL_WHITE, 35},
    {CL_WHITE, 43},
    {CL_WHITE_D, 27},
    {CL_WHITE_D, 19},
    {CL_WHITE_D, 11},
    {CL_WHITE_D, 4},
    {CL_WHITE_D, 13},
    {CL_WHITE_D, 21},
    {CL_BLUE, 40},
    {CL_BLUE, 48},
    {CL_BLUE, 49},
    {CL_BLUE, 50},
    {CL_BLUE, 51},
    {CL_BLUE, 52},
    {CL_BLUE, 53},
    {CL_BLUE_D, 32},
    {CL_BLUE_D, 41},
    {CL_BLUE_D, 42},
    {CL_BLUE_D, 44},
    {CL_BLUE_D, 45},
    {CL_BLUE_D, 54},
};
static const Pix CL_2[] = {
    {CL_WHITE, 21},
    {CL_WHITE, 28},
    {CL_WHITE, 36},
    {CL_WHITE, 43},
    {CL_WHITE_D, 20},
    {CL_WHITE_D, 13},
    {CL_WHITE_D, 22},
    {CL_WHITE_D, 29},
    {CL_BLUE, 40},
    {CL_BLUE, 41},
    {CL_BLUE, 48},
    {CL_BLUE, 49},
    {CL_BLUE, 51},
    {CL_BLUE, 52},
    {CL_BLUE_D, 32},
    {CL_BLUE_D, 33},
    {CL_BLUE_D, 42},
    {CL_BLUE_D, 53},
    {CL_YELLOW_D, 50},
};
static const Pix CL_3[] = {
    {CL_WHITE, 29},
    {CL_WHITE, 36},
    {CL_WHITE, 43},
    {CL_WHITE_D, 28},
    {CL_WHITE_D, 21},
    {CL_WHITE_D, 22},
    {CL_WHITE_D, 30},
    {CL_WHITE_D, 37},
    {CL_BLUE, 24},
    {CL_BLUE, 32},
    {CL_BLUE, 33},
    {CL_BLUE, 41},
    {CL_BLUE, 42},
    {CL_BLUE, 51},
    {CL_BLUE_D, 16},
    {CL_BLUE_D, 25},
    {CL_BLUE_D, 34},
    {CL_BLUE_D, 52},
    {CL_YELLOW, 50},
    {CL_YELLOW_D, 49},
};
static const Pix CL_4[] = {
    {CL_WHITE, 37},
    {CL_WHITE, 44},
    {CL_WHITE, 43},
    {CL_WHITE_D, 36},
    {CL_WHITE_D, 29},
    {CL_WHITE_D, 30},
    {CL_WHITE_D, 38},
    {CL_WHITE_D, 45},
    {CL_BLUE, 0},
    {CL_BLUE, 8},
    {CL_BLUE, 17},
    {CL_BLUE, 25},
    {CL_BLUE, 25},
    {CL_BLUE, 34},
    {CL_BLUE, 42},
    {CL_BLUE, 51},
    {CL_BLUE_D, 1},
    {CL_BLUE_D, 9},
    {CL_BLUE_D, 18},
    {CL_BLUE_D, 26},
    {CL_BLUE_D, 35},
    {CL_BLUE_D, 52},
    {CL_YELLOW, 50},
    {CL_YELLOW_D, 49},
};
static const Pix CL_5[] = {
    {CL_WHITE, 38},
    {CL_WHITE, 45},
    {CL_WHITE, 44},
    {CL_WHITE, 51},
    {CL_WHITE_D, 37},
    {CL_WHITE_D, 46},
    {CL_BLUE, 1},
    {CL_BLUE, 9},
    {CL_BLUE, 17},
    {CL_BLUE, 26},
    {CL_BLUE, 34},
    {CL_BLUE, 42},
    {CL_BLUE_D, 2},
    {CL_BLUE_D, 10},
    {CL_BLUE_D, 18},
    {CL_BLUE_D, 27},
    {CL_BLUE_D, 35},
    {CL_BLUE_D, 43},
    {CL_YELLOW, 49},
    {CL_YELLOW, 50},
    {CL_YELLOW_D, 48},
};
static const Pix CL_6[] = {
    {CL_WHITE, 46},
    {CL_WHITE, 45},
    {CL_WHITE, 52},
    {CL_WHITE_D, 37},
    {CL_WHITE_D, 38},
    {CL_WHITE_D, 53},
    {CL_WHITE_D, 54},
    {CL_BLUE, 2},
    {CL_BLUE, 10},
    {CL_BLUE, 18},
    {CL_BLUE, 27},
    {CL_BLUE, 35},
    {CL_BLUE, 43},
    {CL_BLUE_D, 3},
    {CL_BLUE_D, 11},
    {CL_BLUE_D, 19},
    {CL_BLUE_D, 28},
    {CL_BLUE_D, 36},
    {CL_BLUE_D, 44},
    {CL_YELLOW, 49},
    {CL_YELLOW, 50},
    {CL_YELLOW, 51},
    {CL_YELLOW_D, 41},
    {CL_YELLOW_D, 48},
};
static const Pix CL_7[] = {
    {CL_WHITE, 54},
    {CL_WHITE, 53},
    {CL_WHITE, 52},
    {CL_WHITE_D, 45},
    {CL_WHITE_D, 46},
    {CL_BLUE, 3},
    {CL_BLUE, 11},
    {CL_BLUE, 19},
    {CL_BLUE, 27},
    {CL_BLUE, 35},
    {CL_BLUE, 43},
    {CL_BLUE_D, 4},
    {CL_BLUE_D, 12},
    {CL_BLUE_D, 20},
    {CL_BLUE_D, 28},
    {CL_BLUE_D, 36},
    {CL_BLUE_D, 44},
    {CL_YELLOW, 48},
    {CL_YELLOW, 49},
    {CL_YELLOW, 50},
    {CL_YELLOW, 51},
    {CL_YELLOW_D, 40},
    {CL_YELLOW_D, 41},
};
static const Pix CL_8[] = {
    {CL_WHITE, 53},
    {CL_WHITE, 52},
    {CL_WHITE_D, 45},
    {CL_WHITE_D, 54},
    {CL_BLUE, 4},
    {CL_BLUE, 12},
    {CL_BLUE, 20},
    {CL_BLUE, 27},
    {CL_BLUE, 35},
    {CL_BLUE, 43},
    {CL_BLUE_D, 5},
    {CL_BLUE_D, 13},
    {CL_BLUE_D, 21},
    {CL_BLUE_D, 28},
    {CL_BLUE_D, 36},
    {CL_BLUE_D, 44},
    {CL_YELLOW, 40},
    {CL_YELLOW, 41},
    {CL_YELLOW, 50},
    {CL_YELLOW, 51},
    {CL_YELLOW_D, 32},
    {CL_YELLOW_D, 33},
    {CL_YELLOW_D, 48},
    {CL_YELLOW_D, 49},
};
static const Pix CL_9[] = {
    {CL_WHITE, 53},
    {CL_WHITE, 52},
    {CL_WHITE_D, 54},
    {CL_BLUE, 5},
    {CL_BLUE, 13},
    {CL_BLUE, 20},
    {CL_BLUE, 28},
    {CL_BLUE, 35},
    {CL_BLUE, 43},
    {CL_BLUE, 50},
    {CL_BLUE_D, 6},
    {CL_BLUE_D, 14},
    {CL_BLUE_D, 21},
    {CL_BLUE_D, 29},
    {CL_BLUE_D, 36},
    {CL_BLUE_D, 44},
    {CL_YELLOW, 32},
    {CL_YELLOW, 41},
    {CL_YELLOW, 42},
    {CL_YELLOW, 51},
    {CL_YELLOW_D, 33},
    {CL_YELLOW_D, 40},
};
static const Pix CL_10[] = {
    {CL_WHITE, 52},
    {CL_WHITE_D, 53},
    {CL_BLUE, 14},
    {CL_BLUE, 21},
    {CL_BLUE, 22},
    {CL_BLUE, 29},
    {CL_BLUE, 36},
    {CL_BLUE, 44},
    {CL_BLUE, 50},
    {CL_BLUE, 51},
    {CL_BLUE_D, 30},
    {CL_BLUE_D, 37},
    {CL_YELLOW, 33},
    {CL_YELLOW, 42},
    {CL_YELLOW, 43},
    {CL_YELLOW_D, 41},
    {CL_YELLOW_D, 32},
    {CL_YELLOW_D, 24},
    {CL_YELLOW_D, 25},
    {CL_YELLOW_D, 34},
};
static const Pix CL_11[] = {
    {CL_WHITE, 52},
    {CL_WHITE_D, 53},
    {CL_BLUE, 22},
    {CL_BLUE, 29},
    {CL_BLUE, 30},
    {CL_BLUE, 36},
    {CL_BLUE, 37},
    {CL_BLUE, 44},
    {CL_BLUE, 50},
    {CL_BLUE, 51},
    {CL_BLUE_D, 38},
    {CL_BLUE_D, 45},
    {CL_YELLOW, 25},
    {CL_YELLOW, 34},
    {CL_YELLOW, 43},
    {CL_YELLOW_D, 33},
    {CL_YELLOW_D, 24},
    {CL_YELLOW_D, 16},
    {CL_YELLOW_D, 17},
    {CL_YELLOW_D, 26},
};
static const Pix CL_12[] = {
    {CL_WHITE_D, 52},
    {CL_BLUE, 38},
    {CL_BLUE, 37},
    {CL_BLUE, 44},
    {CL_BLUE, 50},
    {CL_BLUE, 49},
    {CL_BLUE_D, 51},
    {CL_BLUE_D, 45},
    {CL_BLUE_D, 46},
    {CL_BLUE_D, 53},
    {CL_BLUE_D, 54},
    {CL_YELLOW, 17},
    {CL_YELLOW, 26},
    {CL_YELLOW, 34},
    {CL_YELLOW, 43},
    {CL_YELLOW_D, 25},
    {CL_YELLOW_D, 16},
    {CL_YELLOW_D, 9},
    {CL_YELLOW_D, 18},
};
static const Pix CL_13[] = {
    {CL_BLUE, 38},
    {CL_BLUE, 45},
    {CL_BLUE, 44},
    {CL_BLUE, 42},
    {CL_BLUE, 41},
    {CL_BLUE, 48},
    {CL_BLUE_D, 46},
    {CL_BLUE_D, 49},
    {CL_BLUE_D, 50},
    {CL_BLUE_D, 51},
    {CL_BLUE_D, 52},
    {CL_BLUE_D, 53},
    {CL_BLUE_D, 54},
    {CL_YELLOW, 10},
    {CL_YELLOW, 18},
    {CL_YELLOW, 26},
    {CL_YELLOW, 35},
    {CL_YELLOW, 43},
    {CL_YELLOW_D, 17},
    {CL_YELLOW_D, 9},
    {CL_YELLOW_D, 2},
    {CL_YELLOW_D, 11},
    {CL_YELLOW_D, 19},
    {CL_YELLOW_D, 27},
};
static const Pix CL_14[] = {
    {CL_BLUE, 40},
    {CL_BLUE, 41},
    {CL_BLUE, 42},
    {CL_BLUE, 44},
    {CL_BLUE, 45},
    {CL_BLUE, 46},
    {CL_BLUE_D, 48},
    {CL_BLUE_D, 49},
    {CL_BLUE_D, 50},
    {CL_BLUE_D, 51},
    {CL_BLUE_D, 52},
    {CL_BLUE_D, 53},
    {CL_BLUE_D, 54},
    {CL_YELLOW, 11},
    {CL_YELLOW, 19},
    {CL_YELLOW, 27},
    {CL_YELLOW, 35},
    {CL_YELLOW, 43},
    {CL_YELLOW_D, 18},
    {CL_YELLOW_D, 10},
    {CL_YELLOW_D, 3},
    {CL_YELLOW_D, 12},
    {CL_YELLOW_D, 20},
};
static const Pix CL_15[] = {
    {CL_BLUE, 40},
    {CL_BLUE, 48},
    {CL_BLUE, 49},
    {CL_BLUE, 50},
    {CL_BLUE, 51},
    {CL_BLUE, 52},
    {CL_BLUE, 53},
    {CL_BLUE_D, 32},
    {CL_BLUE_D, 41},
    {CL_BLUE_D, 42},
    {CL_BLUE_D, 44},
    {CL_BLUE_D, 45},
    {CL_BLUE_D, 54},
    {CL_YELLOW, 12},
    {CL_YELLOW, 20},
    {CL_YELLOW, 28},
    {CL_YELLOW, 35},
    {CL_YELLOW, 43},
    {CL_YELLOW_D, 27},
    {CL_YELLOW_D, 19},
    {CL_YELLOW_D, 11},
    {CL_YELLOW_D, 4},
    {CL_YELLOW_D, 13},
    {CL_YELLOW_D, 21},
};
static const Pix CL_16[] = {
    {CL_WHITE_D, 50},
    {CL_BLUE, 32},
    {CL_BLUE, 33},
    {CL_BLUE, 42},
    {CL_BLUE, 52},
    {CL_BLUE, 53},
    {CL_BLUE_D, 40},
    {CL_BLUE_D, 41},
    {CL_BLUE_D, 48},
    {CL_BLUE_D, 49},
    {CL_BLUE_D, 51},
    {CL_YELLOW, 21},
    {CL_YELLOW, 28},
    {CL_YELLOW, 36},
    {CL_YELLOW, 43},
    {CL_YELLOW_D, 20},
    {CL_YELLOW_D, 13},
    {CL_YELLOW_D, 22},
    {CL_YELLOW_D, 29},
};
static const Pix CL_17[] = {
    {CL_WHITE, 50},
    {CL_WHITE_D, 49},
    {CL_BLUE, 16},
    {CL_BLUE, 24},
    {CL_BLUE, 25},
    {CL_BLUE, 33},
    {CL_BLUE, 34},
    {CL_BLUE, 42},
    {CL_BLUE, 51},
    {CL_BLUE, 52},
    {CL_BLUE_D, 32},
    {CL_BLUE_D, 41},
    {CL_YELLOW, 29},
    {CL_YELLOW, 36},
    {CL_YELLOW, 43},
    {CL_YELLOW_D, 28},
    {CL_YELLOW_D, 21},
    {CL_YELLOW_D, 22},
    {CL_YELLOW_D, 30},
    {CL_YELLOW_D, 37},
};
static const Pix CL_18[] = {
    {CL_WHITE, 50},
    {CL_WHITE_D, 49},
    {CL_BLUE, 1},
    {CL_BLUE, 9},
    {CL_BLUE, 18},
    {CL_BLUE, 26},
    {CL_BLUE, 35},
    {CL_BLUE, 51},
    {CL_BLUE, 52},
    {CL_BLUE_D, 0},
    {CL_BLUE_D, 8},
    {CL_BLUE_D, 17},
    {CL_BLUE_D, 25},
    {CL_BLUE_D, 34},
    {CL_BLUE_D, 42},
    {CL_YELLOW, 37},
    {CL_YELLOW, 44},
    {CL_YELLOW, 43},
    {CL_YELLOW_D, 36},
    {CL_YELLOW_D, 29},
    {CL_YELLOW_D, 30},
    {CL_YELLOW_D, 38},
    {CL_YELLOW_D, 45},
};
static const Pix CL_19[] = {
    {CL_WHITE, 49},
    {CL_WHITE, 50},
    {CL_WHITE_D, 48},
    {CL_BLUE, 2},
    {CL_BLUE, 10},
    {CL_BLUE, 18},
    {CL_BLUE, 27},
    {CL_BLUE, 35},
    {CL_BLUE, 43},
    {CL_BLUE_D, 1},
    {CL_BLUE_D, 9},
    {CL_BLUE_D, 17},
    {CL_BLUE_D, 26},
    {CL_BLUE_D, 34},
    {CL_BLUE_D, 42},
    {CL_YELLOW, 38},
    {CL_YELLOW, 45},
    {CL_YELLOW, 44},
    {CL_YELLOW, 51},
    {CL_YELLOW_D, 37},
    {CL_YELLOW_D, 46},
};
static const Pix CL_20[] = {
    {CL_WHITE, 49},
    {CL_WHITE, 50},
    {CL_WHITE, 51},
    {CL_WHITE_D, 48},
    {CL_WHITE_D, 41},
    {CL_BLUE, 3},
    {CL_BLUE, 11},
    {CL_BLUE, 19},
    {CL_BLUE, 28},
    {CL_BLUE, 36},
    {CL_BLUE, 44},
    {CL_BLUE_D, 2},
    {CL_BLUE_D, 10},
    {CL_BLUE_D, 18},
    {CL_BLUE_D, 27},
    {CL_BLUE_D, 35},
    {CL_BLUE_D, 43},
    {CL_YELLOW, 46},
    {CL_YELLOW, 45},
    {CL_YELLOW, 52},
    {CL_YELLOW_D, 37},
    {CL_YELLOW_D, 38},
    {CL_YELLOW_D, 53},
    {CL_YELLOW_D, 54},
};
static const Pix CL_21[] = {
    {CL_WHITE, 48},
    {CL_WHITE, 49},
    {CL_WHITE, 50},
    {CL_WHITE, 51},
    {CL_WHITE_D, 40},
    {CL_WHITE_D, 41},
    {CL_BLUE, 4},
    {CL_BLUE, 12},
    {CL_BLUE, 20},
    {CL_BLUE, 28},
    {CL_BLUE, 36},
    {CL_BLUE, 44},
    {CL_BLUE_D, 3},
    {CL_BLUE_D, 11},
    {CL_BLUE_D, 19},
    {CL_BLUE_D, 27},
    {CL_BLUE_D, 35},
    {CL_BLUE_D, 43},
    {CL_YELLOW, 52},
    {CL_YELLOW, 53},
    {CL_YELLOW, 54},
    {CL_YELLOW_D, 45},
    {CL_YELLOW_D, 46},
};
static const Pix CL_22[] = {
    {CL_WHITE, 40},
    {CL_WHITE, 41},
    {CL_WHITE, 50},
    {CL_WHITE, 51},
    {CL_WHITE_D, 49},
    {CL_WHITE_D, 48},
    {CL_WHITE_D, 32},
    {CL_WHITE_D, 33},
    {CL_BLUE, 5},
    {CL_BLUE, 13},
    {CL_BLUE, 21},
    {CL_BLUE, 28},
    {CL_BLUE, 36},
    {CL_BLUE, 44},
    {CL_BLUE_D, 4},
    {CL_BLUE_D, 12},
    {CL_BLUE_D, 20},
    {CL_BLUE_D, 27},
    {CL_BLUE_D, 35},
    {CL_BLUE_D, 43},
    {CL_YELLOW, 52},
    {CL_YELLOW, 53},
    {CL_YELLOW_D, 45},
    {CL_YELLOW_D, 54},
};
static const Pix CL_23[] = {
    {CL_WHITE, 40},
    {CL_WHITE, 41},
    {CL_WHITE, 42},
    {CL_WHITE, 51},
    {CL_WHITE_D, 32},
    {CL_WHITE_D, 33},
    {CL_BLUE, 6},
    {CL_BLUE, 14},
    {CL_BLUE, 21},
    {CL_BLUE, 29},
    {CL_BLUE, 36},
    {CL_BLUE, 44},
    {CL_BLUE_D, 5},
    {CL_BLUE_D, 13},
    {CL_BLUE_D, 20},
    {CL_BLUE_D, 28},
    {CL_BLUE_D, 35},
    {CL_BLUE_D, 43},
    {CL_BLUE_D, 50},
    {CL_YELLOW, 52},
    {CL_YELLOW, 53},
    {CL_YELLOW_D, 54},
};
static const Pix CL_24[] = {
    {CL_WHITE, 33},
    {CL_WHITE, 42},
    {CL_WHITE, 43},
    {CL_WHITE_D, 41},
    {CL_WHITE_D, 32},
    {CL_WHITE_D, 24},
    {CL_WHITE_D, 25},
    {CL_WHITE_D, 34},
    {CL_BLUE, 22},
    {CL_BLUE, 30},
    {CL_BLUE, 37},
    {CL_BLUE, 45},
    {CL_BLUE_D, 14},
    {CL_BLUE_D, 21},
    {CL_BLUE_D, 29},
    {CL_BLUE_D, 36},
    {CL_BLUE_D, 44},
    {CL_BLUE_D, 51},
    {CL_YELLOW, 52},
    {CL_YELLOW_D, 53},
};
static const Pix CL_25[] = {
    {CL_WHITE, 25},
    {CL_WHITE, 34},
    {CL_WHITE, 43},
    {CL_WHITE_D, 33},
    {CL_WHITE_D, 24},
    {CL_WHITE_D, 16},
    {CL_WHITE_D, 17},
    {CL_WHITE_D, 26},
    {CL_BLUE, 30},
    {CL_BLUE, 37},
    {CL_BLUE, 44},
    {CL_BLUE, 51},
    {CL_BLUE_D, 22},
    {CL_BLUE_D, 29},
    {CL_BLUE_D, 36},
    {CL_BLUE_D, 50},
    {CL_YELLOW, 52},
    {CL_YELLOW_D, 53},
};
static const Pix CL_26[] = {
    {CL_WHITE, 17},
    {CL_WHITE, 26},
    {CL_WHITE, 34},
    {CL_WHITE, 43},
    {CL_WHITE_D, 25},
    {CL_WHITE_D, 16},
    {CL_WHITE_D, 9},
    {CL_WHITE_D, 18},
    {CL_BLUE, 51},
    {CL_BLUE, 53},
    {CL_BLUE, 45},
    {CL_BLUE, 46},
    {CL_BLUE_D, 38},
    {CL_BLUE_D, 37},
    {CL_BLUE_D, 44},
    {CL_BLUE_D, 50},
    {CL_BLUE_D, 49},
    {CL_YELLOW_D, 52},
};
static const Pix CL_27[] = {
    {CL_WHITE, 10},
    {CL_WHITE, 18},
    {CL_WHITE, 26},
    {CL_WHITE, 35},
    {CL_WHITE, 43},
    {CL_WHITE_D, 17},
    {CL_WHITE_D, 9},
    {CL_WHITE_D, 2},
    {CL_WHITE_D, 11},
    {CL_WHITE_D, 19},
    {CL_WHITE_D, 27},
    {CL_BLUE, 49},
    {CL_BLUE, 50},
    {CL_BLUE, 51},
    {CL_BLUE, 52},
    {CL_BLUE, 53},
    {CL_BLUE, 54},
    {CL_BLUE, 46},
    {CL_BLUE_D, 38},
    {CL_BLUE_D, 44},
    {CL_BLUE_D, 45},
    {CL_BLUE_D, 42},
    {CL_BLUE_D, 41},
    {CL_BLUE_D, 48},
};
static const Pix* const CL_FRN[] = {
    CL_0,
    CL_1,
    CL_2,
    CL_3,
    CL_4,
    CL_5,
    CL_6,
    CL_7,
    CL_8,
    CL_9,
    CL_10,
    CL_11,
    CL_12,
    CL_13,
    CL_14,
    CL_15,
    CL_16,
    CL_17,
    CL_18,
    CL_19,
    CL_20,
    CL_21,
    CL_22,
    CL_23,
    CL_24,
    CL_25,
    CL_26,
    CL_27,
};
static const uint8_t CL_SZ[] = {
    sizeof(CL_0),
    sizeof(CL_1),
    sizeof(CL_2),
    sizeof(CL_3),
    sizeof(CL_4),
    sizeof(CL_5),
    sizeof(CL_6),
    sizeof(CL_7),
    sizeof(CL_8),
    sizeof(CL_9),
    sizeof(CL_10),
    sizeof(CL_11),
    sizeof(CL_12),
    sizeof(CL_13),
    sizeof(CL_14),
    sizeof(CL_15),
    sizeof(CL_16),
    sizeof(CL_17),
    sizeof(CL_18),
    sizeof(CL_19),
    sizeof(CL_20),
    sizeof(CL_21),
    sizeof(CL_22),
    sizeof(CL_23),
    sizeof(CL_24),
    sizeof(CL_25),
    sizeof(CL_26),
    sizeof(CL_27),
};

uint8_t getClockLen(uint8_t n) {
    return CL_SZ[n] / sizeof(Pix);
}

const Pix* getClockPix(uint8_t n) {
    return CL_FRN[n];
}

const uint8_t clockAmount = sizeof(CL_SZ) / sizeof(CL_SZ[0]);